image: openjdk:8

variables:
   GIT_STRATEGY: clone
   SSL_SELF_SIGNED: "true"
   PROJECTNAME: "osuSkinChecker"

before_script:
  - java -version
  
stages:
   - compile

compile:
  script:
    - chmod -R 777 ./*
    - cd ${PROJECTNAME}
    - ls -l
    - rm -rf ./bin
    - mkdir bin
    - find src -name "*.java" > sources.txt
    - javac -cp . -d ./bin -g -verbose -version -encoding "UTF-8" @sources.txt
    - jar cvfe ${PROJECTNAME}-${CI_PIPELINE_ID}.jar me.roan.osuskinchecker.SkinChecker ./*
    - cd ..
    - mv ./${PROJECTNAME}/${PROJECTNAME}-${CI_PIPELINE_ID}.jar ./${PROJECTNAME}-${CI_PIPELINE_ID}.jar
  stage: compile
  environment: builds
  artifacts:
    name: "${NAME}"
    expire_in: 1 day
    paths:
      - ${PROJECTNAME}-${CI_PIPELINE_ID}.jar
