image: openjdk:8

variables:
   GIT_STRATEGY: clone
   SSL_SELF_SIGNED: "true"
   PROJECTNAME: "osuSkinChecker"

before_script:
  - java -version
  
stages:
   - compile

compile:
  script:
    - chmod -R 777 ./*
    - cd ${PROJECTNAME}
    - ls -l
    - rm -rf ./bin
    - mkdir bin
    - find src -name "*.java" > sources.txt
    - cd src
    - find -type f \( -name "*.*" ! -name "*.java" \) > ../resources.txt
    - cd ..
    - javac -cp . -d ./bin -g -verbose -version -encoding "UTF-8" @sources.txt
    - cd src
    - while read res; do cp --parents $res ../bin; done <../resources.txt
    - cd ..
    - cd bin
    - jar cvfe ${PROJECTNAME}-${CI_PIPELINE_ID}.jar me.roan.osuskinchecker.SkinChecker ./*
    - cd ../../
    - mv ./${PROJECTNAME}/bin/${PROJECTNAME}-${CI_PIPELINE_ID}.jar ./${PROJECTNAME}-${CI_PIPELINE_ID}.jar
  stage: compile
  environment: builds
  artifacts:
    name: "${NAME}"
    expire_in: 1 week
    paths:
      - ${PROJECTNAME}-${CI_PIPELINE_ID}.jar
